# Generated by Django 4.1.4 on 2022-12-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=10)),
                ('l_name', models.CharField(max_length=10)),
                ('designation', models.CharField(max_length=10)),
                ('photo', models.ImageField(upload_to='photos/%Y/%M/%d/')),
                ('fb_link', models.URLField(max_length=100)),
                ('twt_link', models.URLField(max_length=100)),
                ('g_link', models.URLField(max_length=100)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
